### ISSUE TITLE
[Docs] - Visão do produto (Lean inception)

### ISSUE THREAD

**Issue by GRVial** [fga-eps-mds/2024.1-PrintGo-Doc#15]
## Descrição
Documentar a Lean Inception e revisar o canvas MVP, visando garantir que todos os elementos estão corretos e atualizados.
Depende da #24 

## Tarefas
- [x] A documentação deve refletir com precisão a visão do produto discutida na Lean Inception
- [ ] Deve destacar claramente o MVP e suas principais funcionalidades

**Comment by CA1RO** [comment]
Estou com um problema: as imagens estão dando erro 404. Acho que seja por causa do path, mas não consigo entender onde. Enfim, quando conseguir resolver faço o pull request.
