### ISSUE TITLE
[Docs] - Guia de estilo

### ISSUE THREAD

**Issue by GRVial** [fga-eps-mds/2024.1-PrintGo-Doc#19]
## Descrição
Criar documento de guia de estilo (identidade visual) revisando o utilizado semestre passado.

**Comment by Edilson-r-jr** [comment]
[guia_de_estilo.md](https://github.com/user-attachments/files/16401137/guia_de_estilo.md)
![Guia-Figma](https://github.com/user-attachments/assets/67b73aa7-e28e-4800-92f4-a27cd738f425)
![icones](https://github.com/user-attachments/assets/adc5c1fb-8c1e-4ca7-86e4-b49146018c4c)
![primarias](https://github.com/user-attachments/assets/afa8989a-8e5c-465a-ad8b-0f1cd0335da9)
![secundarias](https://github.com/user-attachments/assets/4a7fd60e-c144-4b9f-9c20-6be554c21e76)
![tipografia](https://github.com/user-attachments/assets/a33e40c7-ce39-4c7d-a705-336359b69b85)
