### ISSUE TITLE
[Docs] - Canvas MVP

### ISSUE THREAD

**Issue by GRVial** [fga-eps-mds/2024.1-PrintGo-Doc#24]
## Descrição
O MVP do projeto foi definido na última reunião com os POs, com isso se faz necessário finalizar o canvas MVP.

## Tarefas
- [x] O canvas MVP deve estar elaborado de acordo com o MVP definido no sequenciado.

**Comment by MarcusEscobar** [comment]
![image](https://github.com/user-attachments/assets/0f968dc8-9141-4b2e-9447-306c6dcc418e)

**Comment by DanielViniciusAlves** [comment]
@MarcusEscobar acredito que tem que corrigir o cronograma. Acredito que são 8 semanas.

**Comment by MarcusEscobar** [comment]
Corrigido!!
