### ISSUE TITLE
Configurar SonarCloud

### ISSUE THREAD

**Issue by eliseukadesh67** [fga-eps-mds/2024.1-PrintGo-Doc#56]

**Comment by GRVial** [comment]
Eu e o @DanielViniciusAlves já adicionamos o SonarCloud (acho que falta um só que irei terminar) e configuramos de acordo com as métricas estabelecidas pelo professor. Também já foi configurada a pipeline que recolhe as métricas das releases e cria um log aqui no repositório de documentação.
