### ISSUE TITLE
[Docs] - Ajustar protótipo da US - 03

### ISSUE THREAD

**Issue by eliseukadesh67** [fga-eps-mds/2024.1-PrintGo-Doc#68]
### Descrição

Após a reunião de validação das historias de usuário iniciais, novos criterios de aceitação foram gerados e por consequência mudanças nos protótipos deverão ser feitas para se adaptar os novos critérios.

### Tarefas

- [x] Adicionar os novos campos de acordo com os novos critérios;
- [x] Possibilitar uma listagem de localização para ser selecionada (Schedula);
- [x] Mostrar as localidades regionais e as "filhas" (de acordo com a resposta da api do Schedula)

### Critérios de Aceitação

- [x] Ajustar o protótipo de acordo com os novos critérios de aceitação listados na #28

### Protótipo atual

![Screenshot from 2024-07-24 20-17-59](https://github.com/user-attachments/assets/ed8dbee7-280d-43f9-9e7f-94a983862cb7)

![Screenshot from 2024-07-24 20-15-06](https://github.com/user-attachments/assets/e7382937-005b-4efd-b2de-f11d9f5df5d2)

![Screenshot from 2024-07-24 20-13-24](https://github.com/user-attachments/assets/8d755b56-b888-48a0-be47-9e102b7e5a11)

![Screenshot from 2024-07-24 20-14-10](https://github.com/user-attachments/assets/09dbe56a-b1f0-47bf-bc0d-4fc4f4d267ff)

Link do protótipo desenvolvido por @GustavoHaubert: 

https://www.figma.com/proto/nMiS0y8QcqYYUm4kV6CXba/prototipo-printGo?node-id=84-2545&t=QEnwk3AN26ZcbV5D-0&scaling=contain&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=84%3A2545

**Comment by DanielViniciusAlves** [comment]
<img width="789" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUlOQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3e42fa454091209135adaa29b0fa696971325bad/image.png" alt="image.png" />
<img width="789" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVFOQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ac4376e29b63d3a3a5d7d08b5540d17b4fe11a9c/image.png" alt="image.png" />

![image](https://github.com/user-attachments/assets/53c3a3f4-3318-4323-a0dc-423ad959c908)

<img width="789" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWdOQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--41a466440379f3910b2a99e763b4253b14da4e5d/image.png" alt="image.png" />

**Comment by DanielViniciusAlves** [comment]
Protótipo disponível [aqui](https://www.figma.com/proto/gy1Y7e6FvyasuVFgEUD1xD/US03?t=S4pHFvy3tSrNtkNz-1).

**Comment by eliseukadesh67** [comment]
@DanielViniciusAlves acho que ao inves do simbolo de excluir, poderia ter um "switch" pra ativar/desativar o equipamento ao inves de remover ele, igual ficou no prototipo da #28 na listagem de contratos.
